import "/styles/globals.scss";
import { Inter } from "next/font/google";
import { Roboto_Condensed } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import Header from "/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Internal Geometry",
  description: "Generated by create next app",
};

const font_primary = Roboto_Condensed({
  subsets: ["latin"],
  variable: "--font-primary",
  weight: ["300", "400", "700"],
});

const font_secondary = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-secondary",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font_primary.variable} ${font_secondary.variable}`}>
        <Header />
        <div>
          <main className="c-main">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
